# Generated by Django 3.0.2 on 2020-01-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200128_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='design',
        ),
        migrations.RemoveField(
            model_name='project',
            name='furniture',
        ),
        migrations.RemoveField(
            model_name='project',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='project',
            name='room',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.DeleteModel(
            name='design',
        ),
        migrations.DeleteModel(
            name='furniture',
        ),
        migrations.DeleteModel(
            name='goal',
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.DeleteModel(
            name='room',
        ),
    ]
