# Generated by Django 3.0.2 on 2020-01-28 10:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
                ('content', models.CharField(default='0000000', max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='furniture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phrase', models.CharField(default='111111', max_length=60)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='goal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('goal', models.CharField(default='0000000', max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
                ('content', models.CharField(default='0000000', max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('design', models.ManyToManyField(to='modsy.design')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modsy.furniture')),
                ('goal', models.ManyToManyField(to='modsy.goal')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modsy.room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
